# 代数的確率空間

代数的確率空間は*-代数$A$と状態$\psi$との組

## 例１　複素正方行列全体をAとし、共役転置を$\psi$としたもの

### 複素数体C上の代数（多元環）
```{r}
my.rnormcomplex <- function(n){
  rnorm(n) + 1i * rnorm(n)
}
d <- 2
x <- matrix(my.rnormcomplex(d^2),d,d)
y <- matrix(my.rnormcomplex(d^2),d,d)
z <- matrix(my.rnormcomplex(d^2),d,d)
x+y - (y+x)
lambda <- my.rnormcomplex(1)
lambda * (x * y) - ((lambda*x)*y)
zero <- matrix(0+1i*0,d,d)
one <- diag(rep(1,d))+0*1i
x - (x+zero)
x - (x %*% one)

x %*% y - (y %*% x) # not equal
```

### 対合 involution

```{r}
my.involFx <- function(x){
  t(Conj(x))
}
x - t(my.involFx(x)) # Real = 0

x_ <- my.involFx(x)
y_ <- my.involFx(y)
my.involFx(x+y) - (x_ + y_)
my.involFx(lambda*x) - Conj(lambda) * x_
(my.involFx(x %*% y)) - my.involFx(y) %*% my.involFx(x)
my.involFx(my.involFx(x)) - x
```

### 状態（複素数への写像）として、トレースを次元で割った値を取り上げる

```{r}
my.stateFx <- function(x){
  sum(diag(x))/ncol(x)
}

mu <- my.rnormcomplex(1)

my.stateFx(lambda*x + mu*y) - (lambda*my.stateFx(x) + mu*my.stateFx(y))

my.stateFx(x%*%my.involFx(x)) # >=0　確率密度のようなもの
my.stateFx(one)
```

### 状態は正定値正方行列であって、トレースが１であるようなものに１対１対応する

```{r}
my.stateMat <- function(my.stateFx,d){
  ret <- matrix(0,d,d)
  for(i in 1:d){
    for(j in 1:d){
      tmp <- matrix(0,d,d)
      tmp[i,j] <- 1
      ret[i,j] <- my.stateFx(tmp)
    }
  }
  return(ret)
}
rho <- my.stateMat(my.stateFx,d)
rho
```
### *-代数と状態のペア

```{r}
my.stateFx(my.involFx(x)) - Conj(my.stateFx(x))
# 内積のようなもの
Mod(my.stateFx(my.involFx(x) %*% y))^2 - my.stateFx(my.involFx(x)%*%x) * my.stateFx(my.involFx(y)%*%y) # < 0
```
### ベクトル状態

ある単位ベクトル$\eta$に対して
$$
<\eta, a \eta> = /sum_{i=1}^d \bar{\eta_i} (a \eta)_i
$$
も状態となっている
```{r}
eta <- my.rnormcomplex(d)
eta <- eta/sqrt(sum(Mod(eta)^2))

my.stateFx <-function(x){
  sum(Conj(eta)* (x%*%eta))
}
mu <- my.rnormcomplex(1)

my.stateFx(lambda*x + mu*y) - (lambda*my.stateFx(x) + mu*my.stateFx(y))

my.stateFx(x%*%my.involFx(x)) # >=0　確率密度のようなもの
my.stateFx(one)
```


## 例２　実数全体をAとし、自身への写像を$\psi$としたもの

```{r}
# complex -> real
my.rnormreal <- function(n){
  rnorm(n)
}
d <- 1 # 2 -> 1
x <- matrix(my.rnormreal(d^2),d,d)
y <- matrix(my.rnormreal(d^2),d,d)
z <- matrix(my.rnormreal(d^2),d,d)
x+y - (y+x)
lambda <- my.rnormcomplex(1)
lambda * (x * y) - ((lambda*x)*y)
zero <- matrix(0,d,d)
one <- diag(rep(1,d))
x - (x+zero)
x - (x %*% one)

x %*% y - (y %*% x) # not equal
```

### 対合 involution

```{r}
my.involFx <- function(x){
  t(Conj(x))
}
x - t(my.involFx(x)) # Real = 0

x_ <- my.involFx(x)
y_ <- my.involFx(y)
my.involFx(x+y) - (x_ + y_)
my.involFx(lambda*x) - Conj(lambda) * x_
(my.involFx(x %*% y)) - my.involFx(y) %*% my.involFx(x)
my.involFx(my.involFx(x)) - x
```

### 状態（複素数への写像）として、トレースを次元で割った値を取り上げる

```{r}
my.stateFx <- function(x){
  sum(diag(x))/ncol(x)
}

mu <- my.rnormcomplex(1)

my.stateFx(lambda*x + mu*y) - (lambda*my.stateFx(x) + mu*my.stateFx(y))

my.stateFx(x%*%my.involFx(x)) # >=0
my.stateFx(one)
```

### *-代数と状態のペア

```{r}
my.stateFx(my.involFx(x)) - Conj(my.stateFx(x))
Mod(my.stateFx(my.involFx(x) %*% y))^2 - my.stateFx(my.involFx(x)%*%x) * my.stateFx(my.involFx(y)%*%y) # < 0
```
