---
title: "正三角形でできたグラフ"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## 基本成分

### 正四面体

```{r}
library(igraph)
my.tri4 <- function(name="hoge"){
  el <- rbind(c(1,2),c(1,3),c(1,4),c(2,3),c(3,4),c(4,2))
  el <- matrix(paste(name,el,sep=""),ncol=2)
  g <- graph.edgelist(el,directed=FALSE)
  faces <- rbind(c(1,2,3),c(1,3,4),c(1,4,2),c(2,4,3))
  faces <- matrix(paste(name,faces,sep=""),ncol=3)

  return(list(g=g,faces=faces))
}
my.tri8 <- function(name="hoge"){
  el <- rbind(c(1,2),c(1,3),c(1,4),c(1,5),c(2,3),c(3,4),c(4,5),c(2,5),c(2,6),c(3,6),c(4,6),c(5,6))
  el <- matrix(paste(name,el,sep=""),ncol=2)
  g <- graph.edgelist(el,directed=FALSE)
  faces <- rbind(c(1,2,3),c(1,3,4),c(1,4,5),c(1,5,2),c(3,2,6),c(4,3,6),c(4,6,5),c(2,5,6))
  faces <- matrix(paste(name,faces,sep=""),ncol=3)
  return(list(g=g,faces=faces))
}
my.tri20 <- function(name="hoge"){
  el <- rbind(c(1,2),c(1,3),c(1,4),c(1,5),c(1,6),c(2,3),c(3,4),c(4,5),c(5,6),c(2,6),c(2,7),c(6,7),c(2,8),c(3,8),c(3,9),c(4,9),c(4,10),c(5,10),c(5,11),c(6,11),c(7,8),c(8,9),c(9,10),c(10,11),c(7,11),c(7,12),c(8,12),c(9,12),c(10,12),c(11,12))
  el <- matrix(paste(name,el,sep=""),ncol=2)
  g <- graph.edgelist(el,directed=FALSE)
  faces <- rbind(c(1,2,3),c(1,3,4),c(1,4,5),c(1,5,6),c(1,6,2),c(3,2,7),c(4,3,8),c(5,4,9),c(6,5,10),c(2,6,11),c(2,11,7),c(3,7,8),c(4,8,9),c(5,9,10),c(6,10,11),c(8,7,12),c(9,8,12),c(10,9,12),c(11,10,12),c(7,11,12))
  faces <- matrix(paste(name,faces,sep=""),ncol=3)

  return(list(g=g,faces=faces))
}
```

```{r}
g4 <- my.tri4("A")
plot(g4$g)
```

```{r}
g8 <- my.tri8("B") 
plot(g8$g)
dim(g8$faces)
```

```{r}
g20 <- my.tri20("C") 
plot(g20$g)
```
```{r}
g20$g[] 
```

```{r}
# g1の第i三角形とg2の第j三角形をはり合わせる

my.paste.g <- function(g1,g2,u,v){
  f1 <- g1$faces[u,]
  f2 <- g2$faces[v,]
  el1 <- get.edgelist(g1$g) 
  el2 <- get.edgelist(g2$g) 
  for(i in 1:length(f1)){
    el1[which(el1==f1[i])] <- f2[i]
  }
  new.el <- rbind(el1,el2)
  new.el <- t(apply(new.el,1,sort))
  new.el <- unique(new.el)
  newg <- graph.edgelist(new.el,directed=FALSE)
  new.faces <- rbind(g1$faces[-u,],g2$faces[-v,]) 
  return(list(g=newg,faces=new.faces))
}
```

```{r}
gx <- my.paste.g(g20,g8,1,1) 

plot(gx$g)
gx$faces
```



```{r}

gx$g[]
```


```{r}
g82 <- my.tri8("D")
gx2 <- my.paste.g(gx,g82,10,1) 
plot(gx2$g) 

gx2$g[] 
```