---
title: "三角メッシュグラフの双対グラフのゼータ函数"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(igraph) 
library(complexplus) 
```

## 三角メッシュグラフ

三角メッシュグラフは、全ての面が三角形であるような閉多面体グラフです。

閉曲面に対応する、三角メッシュグラフを$G= (V,E,F,D,H)$のように、頂点集合V、辺集合E、面集合F、頂点の次数D、面の頂点数・辺数(h角形)Hの組で表すことにします。

$$
|V| - |E| + |F| = 2
$$

が成り立ちます。また自然数kを用いて
$$
|V| = |D| = k + 2\\
|E| = 3k\\
|F| = 2k\\
\sum_{i=1}^{|V|} d_i = 6k\\
\forall i \;h_i = 3\\
\sum_{i=1}^{|F|} h_i = 3 \times |F| = 6k
$$
となることも知られています。


## その双対グラフ

その双対グラフ$G_d = (V_d,E_d,F_d,D_d)$も、閉多面体です。

三角メッシュグラフと違うのは、面が三角形ばかりではないことと、全ての頂点次数が3であることです。次数３の正則グラフです。


以下が成り立ちます。
$$
|V_d| - |E_d| + |F_d| = 2
$$

また自然数kを用いて
$$
|V_d| = |D_d| = |F| = 2k\\
|E_d| = = |E| =  3k\\
|F_d| = |V| = k+2\\
\forall i \; f_{d,i} = d_i
\forall i \;d_{d,i} = h_i = 3\\
\sum_{i=1}^{|V_d|} d_{d,i} = 3 \times |V_d| = 6k\\
\sum_{i=1}^{|F_d|} h_{d,i} = \sum_{i=1}^{|F_d|=|V|} d_i = 3 \times |F| = 6k
$$

## グラフの二重エッジ接続行列とグラフのゼータ関数

無向グラフの辺を有向２本にする(二重エッジ)。
二重エッジ集合を
$$
E_w = E \cup \bar{E}\\
E = \{e_i,...,e_{|E|}\}\\
\bar{E} = \{\bar{e_1},...,\bar{e_{|E|}}\}\\
E_w = \{e_{w,1},...,e_{w,|E_w|}\} = \{e_1,...,e_{|E|},\bar{e_1},...,\bar{e_{|E|}}\}
$$
とする。

ちなみに
$|E_w| = 2 \times |E|$である。

閉多面体グラフの場合、$|E|=3k$であるから、二重エッジ集合$|E_w| = 6k$である。

今ある二重エッジ$e_{w,i}$の終点と別の二重エッジ$e_{w,j}$の始点とが同じであるとき、$6k \times 6k$行列の$(i,j)$成分を１とするような行列を、

二重エッジ接続行列とする。

ただし、終点・始点の関係については、２つの二重エッジが同一無向辺からできたものである場合は、接続関係にある、とは見なさないこととする。

## 閉多面体双対グラフの二重エッジ接続行列

双対グラフはまちまちな$h_{d,i}$角形からできています。

$h_{d,i}$角形の辺に関する接続関係は、$h_{d,i} \times h_{d,i}$な置換行列になっています。

$F_d$の全ての面を時計回りに回るサイクルを考えると、全ての二重エッジを１度だけ利用した、$|F_d|$個の相互に独立な置換行列になっています。

それを$S_{clock}$と書くことにします。

逆に、全ての面を反時計回りに回るサイクルも、全ての二重エッジを１度だけ利用した、$|F_d|$個の相互に独立な置換行列になっています。

それを$S_{counter}$と書くことにします。

この双対グラフの二重接続行列は

$$
We_d = S_{clock} + S_{counter}
$$

となっています。

## $S_{clock}$と$S_{counter}$との関係

各面の時計回りサイクルの接続が$e_{w_i} \to e_{w,j}$を含んでいるとき、その面の反時計回りサイクルの接続には、$e_{w,i'} \to e_{w,j'}$が含まれる。

ただし、
$$
i' = j \pm |E|\\
j' = i \pm |E|\\
1 \le i,j,i',j' \le 2|E|
$$

このことから、以下のような関係がある。

$$
W_{counter} = P W_{clock} P
$$
ただし、$P$は(1->1+|E|,2->2+|E|,...,|E|->2|E|,|E|+1->1,|E|+2->2,...,2|E|->|E|)と言う置換に対応する置換行列。


の関係にある

